import Head from "next/head";
import Products from "../components/Products";
import { getProducts } from "../lib/external_fns";
import { useCart } from "../hooks/useCart";
import { Container } from "@mui/material";

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Online Store: Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Products list={data}></Products>
    </div>
  );
}

export async function getStaticProps() {
  const products = await getProducts();
  return {
    props: { data: products },
  };
}
